#!/bin/bash
# Load encrpted v2ray, git keys from private repos
# IyBodHRwczovL2dpc3QuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0t1bmtnZy9mNzFk
# ZjZkZjM1OTEwYWNkNzQ2ZTlhOWFlMDBjMTY5Ni9yYXcvOTNiNjZmMDc1NGExZmEx
# NWYyMzQ3OGY2ZjVjZjhiZmQxMWZodHRwczovL2dpc3QuZ2l0aHVidXNlcmNvbnRl
# bnQuY29tL0t1bmtnZy9mNzFkZjZkZjM1OTEwYWNkNzQ2ZTlhOWFlMDBjMTY5Ni9y
# YXcvOTNiNjZmMDc1NGExZmExNWYyMzQ3OGY2ZjVjZjhiZmQxMWZkYzJiZS9yYW5k
# b20udHh0ZGMyYmUvcmFuZG9tLnR4dAo=

# LTI1Ni1jYmMgLWl0ZXIgMjIgLXBia2RmMgo=

export keys_repo="https://github.com/Kunkgg/arch_setup_keys.git"
